### ISSUE TITLE
unable to install atom-elasticsearch-client-master

### ISSUE THREAD

**Issue by kosckosc** [KunihikoKido/atom-elasticsearch-client#5]
unable to install atom-elasticsearch-client-master
v0.9.0

**Comment by KunihikoKido** [comment]
Please tell me a little bit more in detail about that.

Note: This package has module dependencies that cannot be installed without Git.

**Comment by kosckosc** [comment]
after installing atom eitor I tried to install elasticsearch-client this is error:
Installing “elasticsearch-client@0.9.0” failed.Hide output…
Failed to install elasticsearch-client because Git was not found.

The elasticsearch-client package has module dependencies that cannot be installed without Git.

You need to install Git and add it to your path environment variable in order to install this package.

You can install Git by downloading, installing, and launching GitHub for Windows: https://windows.github.com

Run apm -v after installing Git to see what version has been detected.

**Comment by kosckosc** [comment]
I manage to install other packages without problem.
